spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: prod
    include: secret
logging:
  level:
    root: info
    com.ll.hereispaw : debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always